apiVersion: v1
kind: ReplicationController
metadata:
  name: grafana
  labels:
    name: grafana
spec:
  replicas: 1
  selector:
    name: grafana
  template:
    metadata:
      labels:
        name: grafana
    spec:
      containers:
      - name: master
        image: gordons/grafana:stable
        ports:
        - containerPort: 3000
