apiVersion: v1
kind: ReplicationController
metadata:
  name: rhea-send
  labels:
    name: rhea-send
  annotations:
    prometheus.io/scrape: true
    prometheus.io/port: 9090
spec:
  replicas: 1
  selector:
    name: rhea-send
  template:
    metadata:
      labels:
        name: rhea-send
    spec:
      containers:
      - name: master
        image: gordons/rhea-send:stable
        ports:
        - containerPort: 9090
