kind: ConfigMap
apiVersion: v1
metadata:
  name: maas
data:
  json: |
    {
        "queue1": { "store_and_forward":true, "multicast":false },
        "queue2": { "store_and_forward":true, "multicast":false },
        "anycast": { "store_and_forward":false, "multicast":false },
        "broadcast": { "store_and_forward":false, "multicast":true }
    }
