apiVersion: v1
kind: ReplicationController
metadata:
  name: configured
  labels:
    name: configured
spec:
  replicas: 1
  selector:
    name: configured
  template:
    metadata:
      labels:
        name: configured
    spec:
      containers:
      - name: master
        image: gordons/configured:v9
        ports:
        - containerPort: 55672
