apiVersion: v1
kind: ReplicationController
metadata:
  name: qdrouterd
  labels:
    name: qdrouterd
spec:
  replicas: 1
  selector:
    name: qdrouterd
  template:
    metadata:
      labels:
        name: qdrouterd
    spec:
      containers:
      - name: master
        image: gordons/qdrouterd:v4
        ports:
        - containerPort: 5672
